/* Alex Losser - GradleSkillDrill
 * Due Wed, Jan 27
 * App.java
 * This Java source file was generated by the Gradle 'init' task.
 */

package edu.isu.cs.cs2263;

import com.google.common.collect.Lists;
import javafx.application.Application;
import javafx.beans.Observable;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.ContentDisplay;
import javafx.scene.control.Label;
import javafx.scene.control.ListView;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Region;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

import java.util.List;

public class App  extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception {
        primaryStage.setTitle("Gradle Skilldrill");

        // Components
        ListView listCourse = new ListView();
        Label labelCourse = new Label("Courses:");
        ListView listStudents = new ListView();
        Label labelStudent = new Label("Students:");
        Button buttonLoad = new Button("Load Data");
        Label labelTaking = new Label("Is taking:");

        IOManager manager = new IOManager();

        //Styling
        listCourse.setPrefWidth(600);
        labelTaking.setPadding(new Insets(400, 20, 10, 20));
        labelTaking.setPrefWidth(100);
        labelCourse.setStyle("-fx-font-weight: bold;");
        labelStudent.setStyle("-fx-font-weight: bold;");

//        //JSON Builder Commented out after creation
//            //Make a list of students
//        Student mickey = new Student("Mickey", "Mouse");
//        Student donald = new Student("Donald", "Duck");
//        Student minnie = new Student("Minnie", "Mouse");
//            //Make a list of Courses
//        Course health = new Course(1101, "English", "English and American Literature");
//        Course money = new Course(1404, "Money Management", "Managing Financial Services and Institutions");
//        Course welding = new Course(1601, "AG Welding", "Welding with Gas and AC Equipment");
//        Course cScience = new Course(1440, "Computer Science", "Computer Science and Programming");
//        Course psych = new Course(1118, "Psychology", "The Meaning Behind our Brain");
//        Course physics = new Course(2201, "Physics", "Physics in the Known Universe");
//            //Add Courses to Students
//        mickey.addCourse(health); mickey.addCourse(money); mickey.addCourse(psych);
//        donald.addCourse(money); donald.addCourse(physics); donald.addCourse(welding);
//        minnie.addCourse(cScience); minnie.addCourse(welding); minnie.addCourse(health);
//
//            //Build the JSON file with IOManager
//        List<Student> studentList = Lists.newArrayList(mickey, donald, minnie);
//        manager.writeData(studentList, "./Students.json");
//        //End JSON Creator

        //Actions
        buttonLoad.setOnAction(value -> {
            //Load Action here
            listStudents.getItems().clear();
            List<Student> myStudentList = manager.readData("./Students.json");
            for (Student student : myStudentList) {
                listStudents.getItems().add(student);
            }
        });

        listStudents.setOnMouseClicked(value -> {
            //Load Action Here
            listCourse.getItems().clear();
            Student student = (Student) listStudents.getSelectionModel().getSelectedItem();
            for(Course course : student.getCourses()) {
                listCourse.getItems().add(course);
            }
        });

        //Layouts
        VBox vBoxL = new VBox(labelStudent, listStudents);
        VBox vBoxR = new VBox(labelCourse, listCourse, buttonLoad);
        HBox hBoxTop = new HBox(vBoxL, labelTaking, vBoxR);

        //Scene
        Scene scene = new Scene(hBoxTop, 950, 450);
        primaryStage.setScene(scene);
        primaryStage.show();
    }

    public static void main(String[] args) {
        Application.launch(args);
    }
}
